###
### CFG: GIT - fs is active
###
[kernel]
strict = true
audit = { mode = true, hash = "SHA-256" }
timestamp = { default-time = 00:00:00, timezone = { name = "UTC" } }

[kernel.input]
storage = "fs"
git = { repo = "audit-repo.git", dir = "txns", ref = "set-1e1", suffix = "txn" } 
# git is testing with set-1e2 via overlay, and fs audit data is with old UUID scheme
fs  = { path = "txns", dir = "1E1", suffix = "txn" } 

[transaction]
accounts    = { path = "../../examples/audit/accounts.toml" }
commodities = { path = "../../examples/audit/commodities.toml" }
tags        = { path = "none" }

[report]
report-timezone = "UTC"
scale = { min = 2, max = 7 }
formats = [ "txt", "json" ]
accounts = [ ]
targets = [ "balance", "balance-group", "register" ]

balance       = { title = "BALANCE", type = "tree" }
balance-group = { title = "BALANCE GROUPS", group-by = "month" }
register      = { title = "REGISTER" }

[export]
targets = [ "equity" ]
equity = { equity-account = "Equity:Balance" }
