### 
### TEP-1016: FLAT BALANCE
###
[kernel]
strict = true
audit = { mode = true, hash = "SHA-256" }
timestamp = { default-time = 00:00:00, timezone = { name = "UTC" } }

input = { storage = "git", git = { repo = "audit-repo.git", dir = "txns", ref = "txns-1E2", suffix = "txn" } }

[transaction]
accounts    = { path = "../../examples/audit/accounts.toml" }
commodities = { path = "../../examples/audit/commodities.toml" }
tags        = { path = "none" }


### Report Configuration
[report]
report-timezone = "UTC"
scale = { min = 2, max = 7 }
accounts = [ ]
targets = [ "balance", "balance-group", "register" ]

balance       = { title = "BALANCE", type = "flatter" }
balance-group = { title = "BALANCE GROUPS", type = "tree", group-by = "month" }
register      = { title = "REGISTER" }


### Export Configuration
[export]
targets = [ "equity" ]
equity = { equity-account = "Equity:Balance" }
