###
### GIT-OK
###
[kernel]
strict = true
audit = { mode = false, hash = "SHA-256" }
timestamp = { default-time = 00:00:00, timezone = { name = "UTC" } }

[kernel.input]
storage = "git"

[kernel.input.fs]
dir = "ok/txns-id2id"
suffix = "txn"


[kernel.input.git]
repository = "test-data.git"
dir = "git-txns"
ref = "master"
suffix = ".txn"


[transaction]
accounts    = { path = "id2id-accounts.toml" }
commodities = { path = "none" }
tags        = { path = "none" }

[report]
report-timezone = "UTC"
scale = { min = 2, max = 7 }
formats = [ "txt", "json" ]
accounts = [ ]
targets = [ ]

balance       = { title = "BALANCE" }
balance-group = { title = "BALANCE GROUPS", group-by = "month" }
register      = { title = "REGISTER" }


[export]
targets = [ "identity" ]
equity = { equity-account = "Equity:Balance" }
