### vim: tabstop=4 shiftwidth=4 softtabstop=4 smarttab expandtab autoindent
###
### PRICE: ACCOUNTS
###
accounts = [
    "a",
    "e:conv",
    "e:last",
    "Assets:Cash",
    "Assets:Stocks",
    "Equity:Balance",
]
