accounts = [
   "Assets:Bank:Acme_Inc",
   "Assets:Cash",
   "Assets:Visa:4012_8888_8888_1881",
   "E:0123:567:Sweets:Ice·Cream",
   "E:01234567:Sweets:Ice·Cream",
   "Expenses:Food:FastFood",
   "Expenses:Sweets:Candy",
   "Expenses:Sweets:Ice·Cream",
   "Expenses:crème·glacée",
   "Expenses:ice_cream",
   "Expenses:jäätelö",
   "Expenses:jäätelö:mansikka-vadelma",
   "Expenses:мороженое",
   "Expenses:アイスクリーム",
   "Expenses:風:空",
   "Income:Lottery",
   "assets:cash",
   "空",
   "風:空",
]
